enableDamagePopup: true
levelMultiplier: 2.5
command:
  permission: "dungeons.admin"
disabled_commands:
  - invite
  - kick
  - leave
  - joinparty
dungeons:
  world:
    mobs:
      mob-1:
        type: ZOMBIE
        name: "AFK Zombie"
        invincible: true
        health: 100
        ai: false
        location:
          x: 0
          y: 0
          z: 0
          yaw: 0
          pitch: 0
      mob-2:
        type: SKELETON
        name: "AFK Skeleton"
        invincible: true
        health: 100
        ai: false
        location:
          x: 10
          y: 0
          z: -10
          yaw: 90
          pitch: 0