command:
  permission: "dungeons.admin"
  base-command-name: "dungeons"
  aliases:
    - "dungeon"
  sub-commands:
    "reload":
      base-alias: "reload"
      aliases:
        - "reloadconfig"
dungeons:
  world:
    mobs:
      mob-1:
        type: ZOMBIE
        name: "AFK Zombie"
        invincible: true
        ai: false
        location:
          x: 0
          y: 0
          z: 0
          yaw: 0
          pitch: 0
      mob-2:
        type: SKELETON
        name: "AFK Skeleton"
        invincible: true
        ai: false
        location:
          x: 10
          y: 0
          z: -10
          yaw: 90
          pitch: 0